CREATE TABLE [dbo].[Contracts]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Description] VARCHAR(MAX) NOT NULL, 
    [Price] FLOAT NOT NULL, 
    [DeadLine] DATE NOT NULL, 
    [OwnerId] INT NOT NULL, 
    [DevId] INT NULL,
    CONSTRAINT [FK_CONTRACTS_USEROWNER]FOREIGN KEY (OwnerId) REFERENCES [Users](Id),
    CONSTRAINT [FK_CONTRACTS_USERDEV]FOREIGN KEY (DevId) REFERENCES [Users](Id)
)
