CREATE TABLE [dbo].[NeededSkills]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [ContractId] INT NOT NULL, 
    [SkillId] INT NOT NULL,
    CONSTRAINT [FK_NEEDEDSKILLS_CONTRACTS]FOREIGN KEY (ContractId) REFERENCES [Contracts](Id),
    CONSTRAINT [FK_NEEDEDSKILLS_SKILLS]FOREIGN KEY (SkillId) REFERENCES [Skills](Id)
)
