CREATE TABLE [dbo].[Users]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Email] VARCHAR(50) NOT NULL,
    [Password] VARBINARY(64) NOT NULL, 
    [Salt] VARCHAR(100) NOT NULL, 
    [Name] VARCHAR(50) NOT NULL,
    [Phone] VARCHAR(50) NOT NULL, 
    [IsOwner] BIT NOT NULL 
)
